Vagrant::Config.run do |config|
	config.vm.define :go do |server|
		server.vm.box = "centos-6"
		server.vm.box_url = "http://dl.dropbox.com/u/27749255/centos-6.box"
		server.vm.network("33.33.33.2")
		server.vm.host_name = "go01.local"
		server.vm.customize do |vm|
			vm.memory_size = 1024
		end
		server.vm.provision :puppet do |puppet|
			puppet.manifests_path = "../puppet"
			puppet.manifest_file = "site.pp"
		end
	end

	config.vm.define :builder do |server|
		server.vm.box = "centos-6"
		server.vm.box_url = "http://dl.dropbox.com/u/27749255/centos-6.box"
		server.vm.network("33.33.33.3")
		server.vm.host_name = "builder01.local"
		server.vm.customize do |vm|
			vm.memory_size = 768
		end
		server.vm.provision :puppet do |puppet|
			puppet.manifests_path = "../puppet"
			puppet.manifest_file = "site.pp"
		end
	end

	config.vm.define :app do |server|
		server.vm.box = "centos-6"
		server.vm.box_url = "http://dl.dropbox.com/u/27749255/centos-6.box"
		server.vm.network("33.33.33.4")
		server.vm.host_name = "app01.local"
		server.vm.customize do |vm|
			vm.memory_size = 768
		end
		server.vm.provision :puppet do |puppet|
			puppet.manifests_path = "../puppet"
			puppet.manifest_file = "site.pp"
		end
	end
end
