Vagrant::Config.run do |config|
	config.vm.define :go do |server|
		server.vm.box = "centos-6"
		server.vm.box_url = "http://dl.dropbox.com/u/27749255/centos-6.box"
		server.vm.forward_port("go", 8153, 8153)
		server.vm.forward_port("go-ssl", 8154, 8154)
		server.vm.network("10.0.0.2")
		server.vm.host_name = "go01.local"
		server.vm.customize do |vm|
			vm.memory_size = 1024
		end

		server.vm.provision :puppet do |puppet|
			puppet.module_path = "puppet/modules"
			puppet.manifests_path = "puppet"
			puppet.manifest_file = "site.pp"
		end
	end

	config.vm.define :builder do |server|
		server.vm.box = "centos-6"
		server.vm.box_url = "http://dl.dropbox.com/u/27749255/centos-6.box"
		server.vm.network("10.0.0.3")
		server.vm.forward_port("www", 80, 8000)
		server.vm.host_name = "builder01.local"
		server.vm.customize do |vm|
			vm.memory_size = 512
		end

		server.vm.provision :puppet do |puppet|
			puppet.module_path = "puppet/modules"
			puppet.manifests_path = "puppet"
			puppet.manifest_file = "site.pp"
		end
	end

	config.vm.define :app do |server|
		server.vm.box = "centos-6"
		server.vm.box_url = "http://dl.dropbox.com/u/27749255/centos-6.box"
		server.vm.network("10.0.0.4")
		server.vm.forward_port("www", 80, 8080)
		server.vm.host_name = "app01.local"
		server.vm.customize do |vm|
			vm.memory_size = 256
		end

		server.vm.provision :puppet do |puppet|
			puppet.module_path = "puppet/modules"
			puppet.manifests_path = "puppet"
			puppet.manifest_file = "site.pp"
		end
	end

	config.vm.define :ntf do |server|
		server.vm.box = "centos-6"
		server.vm.box_url = "http://dl.dropbox.com/u/27749255/centos-6.box"
		server.vm.network("10.0.0.5")
		server.vm.forward_port("www", 80, 8080)
		server.vm.host_name = "ntf01.local"
		server.vm.customize do |vm|
			vm.memory_size = 256
		end

		server.vm.provision :puppet do |puppet|
			puppet.module_path = "puppet/modules"
			puppet.manifests_path = "puppet"
			puppet.manifest_file = "site.pp"
		end
	end

	config.vm.define :prod do |server|
		server.vm.box = "centos-6"
		server.vm.box_url = "http://dl.dropbox.com/u/27749255/centos-6.box"
		server.vm.network("10.0.0.6")
		server.vm.forward_port("www", 80, 8081)
		server.vm.host_name = "prod01.local"
		server.vm.customize do |vm|
			vm.memory_size = 256
		end

		server.vm.provision :puppet do |puppet|
			puppet.module_path = "puppet/modules"
			puppet.manifests_path = "puppet"
			puppet.manifest_file = "site.pp"
		end
	end
end
